version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    ports:      
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      #- /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yml:/traefik.yml
      - $PWD/traefik_dynamic.yml:/traefik_dynamic.yml

  whoami:
    image: traefik/whoami
    scale: 2 # Scale 2 service